server:
    port: 8005
spring:
    devtools:
        add-properties: true
    profiles:
        active: dev
    cloud:
        sentinel:
            transport:
                port: 8719
                dashboard: localhost:4000

logging:
  level:
    root: INFO
    web: ERROR
    com:
      github: DEBUG
  file: log.log
